title: Programming Lab
email: milkclouds@naver.com
description: |
  그냥 학생 블로그


baseurl: ''
url: 'http://milkclouds.github.io'
timezone: Asia/Seoul 

repository: milkclouds/milkclouds.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge
 
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: milkclouds@snu.ac.kr
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-133662977-1'
#facebook:
#  username: dellrikee
#twitter:
#  username: kakaodev
github:
  username: milkclouds

disqus_url: milkclouds.disqus.com
disqus_id: milkclouds
disqus_shortname: milkclouds
